In [1]:
import pandas as pd

df = pd.read_csv('quikr_car.csv')
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [3]:
# Show the first 5 rows so you can quickly see what the data looks like
print(df.head())

                                     name   company  year          Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000
1                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000
2              Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000

   kms_driven fuel_type
0  45,000 kms    Petrol
1      40 kms    Diesel
2  22,000 kms    Petrol
3  28,000 kms    Petrol
4  36,000 kms    Diesel

In [4]:
# df.info() shows the column names, data types, and how many non-empty values each column has
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [5]:
# Check how many missing values are in each column
print(df.isnull().sum())

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [6]:
# Check how many duplicate rows are in the dataset
print(df.duplicated().sum())

94

In [7]:
# Show summary statistics for numeric columns
print(df.describe())

              name company  year          Price  kms_driven fuel_type
count          892     892   892            892         840       837
unique         525      48    61            274         258         3
top     Honda City  Maruti  2015  Ask For Price  45,000 kms    Petrol
freq            13     235   117             35          30       440

In [12]:
# Count the rows before removing duplicates
before_rows = len(df)

# drop_duplicates() removes repeated rows from the DataFrame
# inplace=True changes df directly instead of creating a new copy
df.drop_duplicates(inplace=True)

# Count the rows after removing duplicates
after_rows = len(df)

# Show how many duplicate rows were removed
print(f"Removed {before_rows - after_rows} duplicate rows")

# Confirm the remaining duplicate count
print(df.duplicated().sum())

Removed 0 duplicate rows
0

In [13]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [14]:
# Find rows that look unusual or broken in common columns
# We treat a row as abnormal if:
# - year is not a 4-digit number
# - Price is missing or says "Ask For Price"
# - kms_driven does not contain a number followed by "kms"
# - fuel_type is missing

year_ok = df['year'].astype(str).str.fullmatch(r'\d{4}').fillna(False)

abnormal_rows = df[
    (~year_ok)
    | (df['Price'].astype(str).eq('Ask For Price'))
    | (df['Price'].isna())
    | (~df['kms_driven'].astype(str).str.contains(r'\d+\s*kms', na=False))
    | (df['fuel_type'].isna())
]

# Show the suspicious rows so you can inspect them
abnormal_rows

,name,company,year,Price,kms_driven,fuel_type
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
5,Ford EcoSport Titanium 1.5L TDCi,Ford,2015,Ask For Price,"59,000 kms",Diesel
69,I want to sell my car Tata Zest,I,2017,Ask For Price,NaN,NaN
132,Toyota Corolla,Toyota,2009,"2,75,000","26,000 kms",NaN
138,Maruti Suzuki Alto 800 Lxi,Maruti,2018,Ask For Price,"28,028 kms",Petrol
...,...,...,...,...,...,...
882,Maruti Suzuki Alto 800 Select Variant,Maruti,2015,Ask For Price,"70,000 kms",Petrol
884,tata zest 2017 f,tata,sale,"4,50,000",NaN,NaN
887,Ta,Tara,zest,"3,10,000",NaN,NaN
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [18]:
# Clean columns that should contain numbers
# If a value is not a number, pandas changes it to NaN

df['year'] = pd.to_numeric(df['year'], errors='coerce')

# Remove rows where year is not a valid number
before_rows = len(df)
df = df.dropna(subset=['year']).copy()
df['year'] = df['year'].astype(int)
after_rows = len(df)
print(f"Removed {before_rows - after_rows} rows with bad year values")

# Clean kms_driven by removing the word 'kms' and commas first
df['kms_driven'] = df['kms_driven'].astype(str).str.replace(' kms', '', regex=False)
df['kms_driven'] = df['kms_driven'].str.replace(',', '', regex=False)
df['kms_driven'] = pd.to_numeric(df['kms_driven'], errors='coerce')

# Remove rows where kms_driven is not a valid number
before_rows = len(df)
df = df.dropna(subset=['kms_driven']).copy()
df['kms_driven'] = df['kms_driven'].astype(int)
after_rows = len(df)
print(f"Removed {before_rows - after_rows} rows with bad kms_driven values")

# Clean Price by removing commas
df['Price'] = df['Price'].astype(str).str.replace(',', '', regex=False)

# Turn Price into numbers too
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

# Show the cleaned dataset
df

Removed 0 rows with bad year values
Removed 3 rows with bad kms_driven values

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000.0,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000.0,40,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,NaN,22000,Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000.0,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000.0,36000,Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,270000.0,50000,Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,110000.0,30000,Diesel
886,Toyota Corolla Altis,Toyota,2009,300000.0,132000,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000.0,27000,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000.0,40000,Diesel

In [19]:
# Show the full dataset inside a scrollable box
# This is useful when the table is too long to fit on one screen
from IPython.display import display, HTML

display(HTML(f'''
<div style="max-height: 400px; overflow-y: auto; overflow-x: auto; border: 1px solid #ccc; padding: 8px;">
{df.to_html()}
</div>
'''))

In [20]:
# Save the cleaned data to a new CSV file
# index=False keeps the extra row numbers from being written into the file

df.to_csv('quikr_car_cleaned.csv', index=False)

# Confirm the file name that was saved
print('Saved as quikr_car_cleaned.csv')

Saved as quikr_car_cleaned.csv

In [21]:
# Simple total row count - prints the number of rows in the current DataFrame
print('Total rows:', len(df))

Total rows: 746

In [ ]:
# Show the full dataset inside a scrollable box
from IPython.display import display, HTML

display(HTML(f'''
<div style="max-height: 400px; overflow-y: auto; overflow-x: auto; border: 1px solid #ccc; padding: 8px;">
{df.to_html()}
</div>
'''))

AttributeError: 'DataFrame' object has no attribute 'unique'